syntax = "proto3";

package broker;

option go_package = "mbg/api/proto";

service BrokerService {
  rpc Push(PushRequest) returns (PushResponse);
  rpc Pop(PopRequest) returns (PopResponse);
  rpc Ack(AckRequest) returns (AckResponse);
  rpc Nack(NackRequest) returns (NackResponse);
}

message PushRequest {
  string id = 1;
  string payload = 2;
  string headers = 3;
}

message PushResponse {
  bool success = 1;
  string message = 2;
}

message PopRequest {}

message PopResponse {
  string id = 1;
  string payload = 2;
  int64 created_at = 3;
}

message AckRequest {
  string id = 1;
}

message AckResponse {
  bool success = 1;
}

message NackRequest {
  string id = 1;
}

message NackResponse {
  bool success = 1;
}
